html: <center><b>%name%</b><br>%nation%</b><hr>%residents%</center>
y-height: 62
home-marker: https://i.imgur.com/uzklZMv.png
capital-marker: https://i.imgur.com/51isVaU.png
max-distance: 375
debug: true